apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-v##Revision##
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      version: v##Revision##
  template:
    metadata:
      labels:
        app: flask-app
        version: v##Revision##
    spec:
      containers:
        - name: app
          image: dantesaggin/flask-app:v##Revision##
          ports:
            - name: web
              containerPort: 80
              protocol: TCP

