apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-v1
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: flask-app
        version: v1.0.0
    spec:
      containers:
      - name: app
        image: dantesaggin/flask-app:v1
        ports:
        - name: web
          containerPort: 80
        env:
        - name: VERSION
          value: v1.0.0