kind: Service
apiVersion: v1
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: flask-app
    version: v1